[project]
name = "hqfbp"
version = "0.1.0"
description = "Module to handle the HQFBP protocol, aka Hamradio Quick File Broadcasting Protocol"
readme = "README.md"
authors = [
    { name = "Loïc Fejoz", email = "loic@fejoz.net" }
]
requires-python = ">=3.12"
dependencies = [
    "brotli>=1.2.0",
    "cbor2>=5.7.1",
    "reedsolo>=1.7.0",
    "raptorq>=0.1.0",
    "tomlkit>=0.13.2",
]

[project.scripts]
hqfbp-send-udp = "hqfbp.send_udp:main"
hqfbp-receive-udp = "hqfbp.receive_udp:main"
hqfbp-simulate = "hqfbp.simulate:main"

[build-system]
requires = ["uv_build>=0.9.18,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "ruff>=0.9.1",
]
